### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Storyteler** [Tramac/tiny-kinetics-400#1]
感谢分享，你好，从GoogleDrive里边下载的tiny数据集中每个类别有三个视频，而文章中提到只有两个是为什么呀。
还有一点比较疑惑下载好的数据集tiny-kinetics-400底下没有train_256和val_256和文件夹，执行程序时发生报错。下图是我下载数据集的结构。麻烦博主解惑一下
![Kazam_screenshot_00004](https://user-images.githubusercontent.com/19318096/154685153-0c31c00c-d3f6-49f8-b3ce-15ffae938d29.png)
。

**Comment by Tramac** [comment]
你好，tiny-kinetics-400数据集中每个类目下面有三个视频，分别为train、val与test，其中只给出了train与val的meta文件，即tiny_train.csv与tiny_val.csv，如有需要可以把剩余的一个视频组成为tiny_test.csv来使用。

没有train_256和val_256和文件夹可能是你的代码读取数据时的方式不同，建议检查一下dataloader部分，或者使用本代码库中提供的方式。

**Comment by Storyteler** [comment]
多谢您的回答，感激。关于第二个疑惑的地方，其实是执行抽帧的时候出现问题
python ./tools/extract_frames.py --source_dir ~/data/tiny-kinetics-400/train_256 ~/data/kinetics400_30fps_frames/train
在执行extract_frames.py这个文件时，您给的命令示意，后面的 --source_dir ~/data/tiny-kinetics-400/train_256，是视频源路径，这个里面有train_256文件夹，而下载的数据集中只有tiny-kinetics-400，所以想问一下在使用extract_frames.py代码时，我该如何输入命令，我这边是没有train_256 的



在 2022-02-18 21:07:16，"Tramac" ***@***.***> 写道：

你好，tiny-kinetics-400数据集中每个类目下面有三个视频，分别为train、val与test，其中只给出了train与val的meta文件，即tiny_train.csv与tiny_val.csv，如有需要可以把剩余的一个视频组成为tiny_test.csv来使用。

没有train_256和val_256和文件夹可能是你的代码读取数据时的方式不同，建议检查一下dataloader部分，或者使用本代码库中提供的方式。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tramac** [comment]
你需要提前在tiny-kinetics-400目录下新建train_256和val_256两个文件夹

**Comment by Storyteler** [comment]
感谢你的回答，新建train_256和val_256两个文件夹里面放的是不是对应的四百个训练视频和四百个预测视频

**Comment by Tramac** [comment]
对的
