### ISSUE TITLE
decode failed

### ISSUE THREAD

**Issue by YancyGuo** [Tramac/tiny-kinetics-400#2]
hi,我目前在抽取视频帧的脚本上遇到了些问题，希望能占用您几分钟
我的运行指令如下
`python ./tools/extract_frames.py --source_dir ./tiny-Kinetics-400 --target_dir ./tiny-Kinetics-400_30fps_frames
`
并且我的数据集摆放如下图
![image](https://user-images.githubusercontent.com/72378142/211024945-3fd6b459-119f-496e-a56c-32aca3c9e9b2.png)
而chans产生的结果则是全部报decode filed，如下图
``Current class inx:  0
Video ./tiny-Kinetics-400/train_256/abseiling decode failed.
Video ./tiny-Kinetics-400/train_256/air_drumming decode failed.
Video ./tiny-Kinetics-400/train_256/answering_questions decode failed.
Video ./tiny-Kinetics-400/train_256/applauding decode failed.
Video ./tiny-Kinetics-400/train_256/applying_cream decode failed.
Video ./tiny-Kinetics-400/train_256/archery decode failed.
Video ./tiny-Kinetics-400/train_256/arm_wrestling decode failed.
Video ./tiny-Kinetics-400/train_256/arranging_flowers decode failed.
Video ./tiny-Kinetics-400/train_256/assembling_computer decode failed.
Video ./tiny-Kinetics-400/train_256/auctioning decode failed.
Video ./tiny-Kinetics-400/train_256/baby_waking_up decode failed.
Video ./tiny-Kinetics-400/train_256/baking_cookies decode failed.
Video ./tiny-Kinetics-400/train_256/balloon_blowing decode failed.
Video ./tiny-Kinetics-400/train_256/bandaging decode failed.
Video ./tiny-Kinetics-400/train_256/barbequing decode failed.
Video ./tiny-Kinetics-400/train_256/bartending decode failed.
Video ./tiny-Kinetics-400/train_256/beatboxing decode failed.
Video ./tiny-Kinetics-400/train_256/bee_keeping decode failed.
Video ./tiny-Kinetics-400/train_256/belly_dancing decode failed.
Video ./tiny-Kinetics-400/train_256/bench_pressing decode failed.
Video ./tiny-Kinetics-400/train_256/bending_back decode failed.
Video ./tiny-Kinetics-400/train_256/bending_metal decode failed.
Video ./tiny-Kinetics-400/train_256/biking_through_snow decode failed.
Video ./tiny-Kinetics-400/train_256/blasting_sand decode failed.
Video ./tiny-Kinetics-400/train_256/blowing_glass decode failed.
Video ./tiny-Kinetics-400/train_256/blowing_leaves decode failed.
Video ./tiny-Kinetics-400/train_256/blowing_nose decode failed.
Video ./tiny-Kinetics-400/train_256/blowing_out_candles decode failed.
Video ./tiny-Kinetics-400/train_256/bobsledding decode failed.
Video ./tiny-Kinetics-400/train_256/bookbinding decode failed.
Video ./tiny-Kinetics-400/train_256/bouncing_on_trampoline decode failed.
Video ./tiny-Kinetics-400/train_256/bowling decode failed.
Video ./tiny-Kinetics-400/train_256/braiding_hair decode failed.
Video ./tiny-Kinetics-400/train_256/breading_or_breadcrumbing decode failed.
Video ./tiny-Kinetics-400/train_256/breakdancing decode failed.
Video ./tiny-Kinetics-400/train_256/brush_painting decode failed.
Video ./tiny-Kinetics-400/train_256/brushing_hair decode failed.
Video ./tiny-Kinetics-400/train_256/brushing_teeth decode failed.
Video ./tiny-Kinetics-400/train_256/building_cabinet decode failed.
Video ./tiny-Kinetics-400/train_256/building_shed decode failed.
Video ./tiny-Kinetics-400/train_256/bungee_jumping decode failed.
Video ./tiny-Kinetics-400/train_256/busking decode failed.
Video ./tiny-Kinetics-400/train_256/canoeing_or_kayaking decode failed.
Video ./tiny-Kinetics-400/train_256/capoeira decode failed.
Video ./tiny-Kinetics-400/train_256/carrying_baby decode failed.
Video ./tiny-Kinetics-400/train_256/cartwheeling decode failed.
Video ./tiny-Kinetics-400/train_256/carving_pumpkin decode failed.
Video ./tiny-Kinetics-400/train_256/catching_fish decode failed.
Video ./tiny-Kinetics-400/train_256/catching_or_throwing_baseball decode failed.
Video ./tiny-Kinetics-400/train_256/catching_or_throwing_frisbee decode failed.
Video ./tiny-Kinetics-400/train_256/catching_or_throwing_softball decode failed.
Video ./tiny-Kinetics-400/train_256/celebrating decode failed.
Video ./tiny-Kinetics-400/train_256/changing_oil decode failed.
Video ./tiny-Kinetics-400/train_256/changing_wheel decode failed.
Video ./tiny-Kinetics-400/train_256/checking_tires decode failed.
Video ./tiny-Kinetics-400/train_256/cheerleading decode failed.
Video ./tiny-Kinetics-400/train_256/chopping_wood decode failed.
Video ./tiny-Kinetics-400/train_256/clapping decode failed.
Video ./tiny-Kinetics-400/train_256/clay_pottery_making decode failed.
Video ./tiny-Kinetics-400/train_256/clean_and_jerk decode failed.
Video ./tiny-Kinetics-400/train_256/cleaning_floor decode failed.
Video ./tiny-Kinetics-400/train_256/cleaning_gutters decode failed.
Video ./tiny-Kinetics-400/train_256/cleaning_pool decode failed.
Video ./tiny-Kinetics-400/train_256/cleaning_shoes decode failed.
Video ./tiny-Kinetics-400/train_256/cleaning_toilet decode failed.
Video ./tiny-Kinetics-400/train_256/cleaning_windows decode failed.
Video ./tiny-Kinetics-400/train_256/climbing_a_rope decode failed.
Video ./tiny-Kinetics-400/train_256/climbing_ladder decode failed.
Video ./tiny-Kinetics-400/train_256/climbing_tree decode failed.
Video ./tiny-Kinetics-400/train_256/contact_juggling decode failed.
Video ./tiny-Kinetics-400/train_256/cooking_chicken decode failed.
Video ./tiny-Kinetics-400/train_256/cooking_egg decode failed.
Video ./tiny-Kinetics-400/train_256/cooking_on_campfire decode failed.
Video ./tiny-Kinetics-400/train_256/cooking_sausages decode failed.
Video ./tiny-Kinetics-400/train_256/counting_money decode failed.
Video ./tiny-Kinetics-400/train_256/country_line_dancing decode failed.
Video ./tiny-Kinetics-400/train_256/cracking_neck decode failed.
Video ./tiny-Kinetics-400/train_256/crawling_baby decode failed.
Video ./tiny-Kinetics-400/train_256/crossing_river decode failed.
Video ./tiny-Kinetics-400/train_256/crying decode failed.
Video ./tiny-Kinetics-400/train_256/curling_hair decode failed.
Video ./tiny-Kinetics-400/train_256/cutting_nails decode failed.
Video ./tiny-Kinetics-400/train_256/cutting_pineapple decode failed.
Video ./tiny-Kinetics-400/train_256/cutting_watermelon decode failed.``
不知道是指令问题还是数据集拜访问题，希望能得到您的回复，十分感谢

**Comment by Tramac** [comment]
可以检查一下ffmpeg是否可以正常使用

**Comment by YancyGuo** [comment]
ffmpeg检测输出是没有问题的，后续用mmaction的脚本抽成功了，十分感谢您提供的数据集。

**Comment by jiajiajun** [comment]
> 

您好，我也跟您一样decode失败了，请问您是用的mmaction里的哪个脚本解决的呢？多谢！

**Comment by YancyGuo** [comment]
[传送门](https://github.com/open-mmlab/mmaction2/tree/b7af9d329b610f32e29b6c1885330bb7d0afc942/tools/data)，然后具体的抽帧处理在官方手册——dataset preparation

**Comment by jiajiajun** [comment]
> [传送门](https://github.com/open-mmlab/mmaction2/tree/b7af9d329b610f32e29b6c1885330bb7d0afc942/tools/data)，然后具体的抽帧处理在官方手册——dataset preparation
已找到并解决，非常感谢！！

**Comment by SchuckLee** [comment]
我一开始用cmd没有切换当前目录也遇到了这个问题，后续使用pycharm terminal成功运行。。小白也不懂怎么回事，希望给后来人一点经验。
